###
GET http://localhost:8080/v1/empleados/listas
###

###
GET http://localhost:8080/v1/productos/listas
###

###
GET http://localhost:8080/v1/registros/listas
###

###
GET http://localhost:8080/v1/clientes/listas
###

###
GET http://localhost:8080/v1/ventas/listas
###

###
GET http://localhost:8080/v1/ventas/detalles/2
###

###
POST http://localhost:8080/v1/empleados/sesion
Content-Type: application/json

{
  "alias": "user1",
  "clave": "pasds1234"
}
###

###
POST http://localhost:8080/v1/clientes/registro
Content-Type: application/json

{
  "nombre": "user1",
  "apellido": "pass1234",
  "carnet": "10930436AC-JO",
  "telefono": "7756052"
}
###

###
PUT http://localhost:8080/v1/clientes/modificacion/5
Content-Type: application/json

{
  "nombre": "user1",
  "apellido": "pass1234",
  "carnet": "10930436AC-JO",
  "telefono": "7756052"
}
###

###
POST http://localhost:8080/v1/empleados/registro
Content-Type: application/json

{
  "nombre": "user1",
  "apellido": "pass1234",
  "carnet": "10930436AC-JO",
  "alias": "7756052",
  "clave": "d"
}
###

###
PUT http://localhost:8080/v1/empleados/modificacion/3
Content-Type: application/json

{
  "nombre": "user1",
  "apellido": "pass1234",
  "carnet": "10930436AC-JO",
  "alias": "7756052",
  "clave": "sadfasadfsdsafsd"
}
###

###
POST http://localhost:8080/v1/productos/registro
Content-Type: application/json

{
  "nombre": "Producto 2",
  "modelo": "Modelo 2",
  "cantidad": 100,
  "descripcion": "Descripción del producto",
  "precio": "199.99",
  "idMarca": 1,
  "idCategoria": 1,
  "idEmpleado": 2
}
###